apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: remote-jwks-go
  name: remote-jwks-go
  namespace: envoy-yang
spec:
  selector:
    matchLabels:
      app: remote-jwks-go
  template:
    metadata:
      labels:
        app: remote-jwks-go
    spec:
      containers:
        - args:
            - jwks
            - -c
            - /app/jwks.json
          command:
            - main
          image: release-ci.daocloud.io/skoala/demo/remote-jwks-go:0.1.0
          imagePullPolicy: IfNotPresent
          name: remote-jwks-go
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /app/jwks.json
              subPath: jwks.json
      volumes:
        - name: config
          configMap:
            name: jwks-config
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534

---
apiVersion: v1
kind: Service
metadata:
  name: remote-jwks-go
  namespace: envoy-yang
  labels:
    app: remote-jwks-go
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: remote-jwks-go

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jwks-config
  namespace: envoy-yang
  labels:
    app: remote-jwks-go
data:
  jwks.json: |+
    {
      "keys": [
        {
          "p": "8YYH7ZX8ZEt-LAVQgGfJYTkLhKDr0eKrPZQw685MyHadEoMT_f0i911Xluxx8TolF3PAXYWk3rGvIb-RnhOGAtkz2Xh6NIdDaceoD2ZAOxOIg5swE7WCzExkUoVbB6q4xhH7ZbofYAuhE0-NnOj-1ygjytzwYyj1nA-ak7vs7is",
          "kty": "RSA",
          "q": "5d04fHfMrH6X_D1xUZgc58uWa1-LoDoAKpqSM6JcqrJXRENlCA-lRmcFX95wx8F7Nw3dVnSfWR-WSiDOH0uDHODMPpporoDBWx4FqYp-Q3mqD9GAGbuz6SN4bzvBpIQES0iSHPiVZNl5TuP28UHsRlHNMo58lSSk6zA9Udw1Lxc",
          "d": "lDPlkAhr1A60ynrV9yYJEFw-QGkMFwOnhmUsXJwxmQSw2M2DP0N4Dv_IUCOVjaR89cM3SeHT4ByCI02s1H0Li0YfTcZ4xfF_-QXYxAX3IYJlRiSloh8Gl9EuqsiLVZUpi0w5ESQXQu6kyXGfavnpRyd8Y15JBxQEY9rusN2ULs81grvd5Ppv1FQvVVptRFL_14fUgAM-xxOx9R1EwaTdKPW9azi-drRQZanP9IRHi6maOQzFuYDeL6oouKhvxLQSVh1nyhitDOEDauloh96fwpeRfNDKHyV08lm_gAFbPXrDhWivPZA-6jDCNTeIOnoPFHIDB8fokkovhlAP3e5TFQ",
          "e": "AQAB",
          "use": "sig",
          "kid": "secret",
          "qi": "sqY36PRpYoK8m-3aJCvP8KXc3XVgfpbHG-GPfSbNVIPsV5F600GHRkmpLaXgZbj6-Kfe9wzp_R48D8F9jfBZYOV9j4v4olXy4qJwlwYpfW297SWGZoePeSInHXXEKCl-MTVxWGCND0GF7wswmLytmqPT7R40vFHYPwKi0SGLD6w",
          "dp": "K7JVIt388ORbqnk3rFOaspVQiSlYIPwCgTybcT481BPprRy79DrlJZ3kp_CVWNBtP4X4qrLwNj4tckynetMLbt5_K_xJF9HVF4FA3bBhNI7_Jthf5WD0jiPQDsIDyypPDb7ZHfmDjavs84J0G4xn9uNTPnOkpjwV26tTCyF350s",
          "alg": "RS256",
          "dq": "exwMUL1o5Um35OSTeHvbn1muajt18I6f4DGA9B6VOubhTjI6PiMDBb3PZxUfmhzJ_SZz0QYNAhKkz3babnBm_GR5f137itpytHZT2gXOshzLNEWkMiQRq1_P9OMwRwhdtGRdvR52BNlk2xfE_lmsTc0p9VXS654ApeXkMZ-a7Gk",
          "n": "2N2bFx7zd7k39cz1i6KC3-DOTbit5vlg2HSTRpnOSiYc9yvBfq_C7A5gnEX5C4SSxoQIa46-Ljioadu0WyspScA8eV7_FQTi-671SCgTS0VDuzbAcuTtery4a0W30d0dxuhmpK7Xc4NSfL9CqyGskJJwm-aIMiVvt6e28vamJFKkzpZ4rhjAHnLA7lZC3vXIN9ElSmmMkTV8uvs35eqn_c9XgbdyFu09vQN9fCNu4wUYYsFwFc8tNLx-EETPAu2RTa6G5zDHYu_SZ03FeiCyp1O3phEBV-auKkk-n5q0cPDNhJPb5B4Wj6XX7rJDOGGQallKnjSs9OnkpSIbpOpK3Q"
        }
      ]
    }
